### PR TITLE
Fix kotsadm dev workflow

### PR DESCRIPTION
**Pull request by MikaelSmith**

### CODE REVIEW

**Comment by MikaelSmith** [comment]
I'm trying to get the dev workflow with `skaffold dev` working. Currently stuck on
```
...
Waiting for deployments to stabilize...
 - deployment/kotsadm-web is ready. [3/4 deployment(s) still pending]
 - deployment/kotsadm: waiting for init container init-dex-db to complete
    - pod/kotsadm-86995d9dbf-gjr27: waiting for init container init-dex-db to complete
      > [kotsadm-86995d9dbf-gjr27 init-dex-db] sleeping...
      > [kotsadm-86995d9dbf-gjr27 init-dex-db] sleeping...
 - deployment/kotsadm-operator: creating container kotsadm-operator
    - pod/kotsadm-operator-75b464d8fb-dwpnv: creating container kotsadm-operator
 - deployment/kurl-proxy: creating container proxy
    - pod/kurl-proxy-8674767554-khrts: creating container proxy
 - deployment/kotsadm-operator is ready. [2/4 deployment(s) still pending]
 - deployment/kurl-proxy is ready. [1/4 deployment(s) still pending]
 - deployment/kotsadm: container kotsadm terminated with exit code 1
    - pod/kotsadm-86995d9dbf-gjr27: container kotsadm terminated with exit code 1
      > [kotsadm-86995d9dbf-gjr27 kotsadm] standard_init_linux.go:211: exec user process caused "exec format error"
 - deployment/kotsadm failed. Error: container kotsadm terminated with exit code 1.
Cleaning up...
...
```

**Comment by MikaelSmith** [comment]
Oh yeah, trying to run a macOS binary in a Linux container. I'll update the CONTRIBUTING docs to mention how to set it up if you're running a non-Linux workstation.

**Comment by MikaelSmith** [comment]
Ok, got it running now.

**Comment by marccampbell** [comment]
@MikaelSmith thanks.  Yeah, our team develops on remote linux servers, but this is a good catch. Sorry for the confusion!

**Comment by MikaelSmith** [comment]
Any chance of getting this merged?

**Review by laverya — APPROVED** [review]

**Pull request merged**
