### PR TITLE
Config vars proposal

### PR DESCRIPTION
**Pull request by emosbaugh**

### CODE REVIEW

**Comment by emosbaugh** [comment]
as a counter argument for this, the same can be achieved with the following yaml. although im not sure how regen can work.

```yaml
apiVersion: kots.io/v1beta1
kind: Config
metadata:
  name: sentry-enterprise
spec:
  config:
    items:
      - name: certkeyhidden
        type: hidden
        value: '{{repl $cert := genSelfSignedCert (ConfigOption "hostname") nil nil 365 }}{{repl b64enc $cert.Cert }}|{{repl b64enc $cert.Key }}'
      - name: cert
        type: textarea
        value: |
          {{repl ConfigOption "certkeyhidden" | splitList "|" | index 0 | b64dec | nindent 12 }}
      - name: key
        type: textarea
        value: |
          {{repl ConfigOption "certkeyhidden" | splitList "|" | index 1 | b64dec | nindent 12 }}
```

**Comment by laverya** [comment]
I have to say I prefer option 1 to option 2 
But "not building anything" beats that IMO

**Comment by emosbaugh** [comment]
@laverya with the example i gave, how would i regenerate the keypair?

**Comment by AmberAlston** [comment]
Closing this PR out due to its age and time since last update. If this is something we'd like to do moving forward we can re-open this PR or start a new one.

**Pull request closed without merging**
