### PR TITLE
get minio, posgres_alpine and dex image tags from env file for airgap build

### PR DESCRIPTION
**Pull request by jala-dx**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by emosbaugh** [comment]
This doesn't feel right. What's the reason for this?

**Comment by jala-dx** [comment]
> This doesn't feel right. What's the reason for this?

@emosbaugh the image tags have to come from .image.env file instead of hardcoding in the Makefile. Is my assumption incorrect here?

**Comment by emosbaugh** [comment]
This changed a lot since I made my first comment

**Comment by jala-dx** [comment]
> This changed a lot since I made my first comment

Two things changed since you commented on the PR. (Sorry I dint check my email so dint know you commented and force pushed it)

**Comment by emosbaugh** [comment]
Can you fill out the pull request template?

**Review by emosbaugh — COMMENTED** [review]
I think you should discuss this with @murphybytes . There is a mix of make and bash for setting and retrieving these vars. I think we can clean this up a bit and be consistent

**Comment by murphybytes** [comment]
This won't work.  I've submitted a different that fixes the problem PR https://github.com/replicatedhq/kots/pull/2197

**Comment by jala-dx** [comment]
> This won't work. I've submitted a different that fixes the problem PR #2197

nice . Exporting the .image.env before Makefile gets it is a much better option.

**Pull request closed without merging**
