### PR TITLE
Initial design of dashboard links respecting the browser address

### PR DESCRIPTION
**Pull request by marccampbell**

### CODE REVIEW

**Comment by divolgin** [comment]
Will this support templated links set via config options, in which case it will be different from localhost and from the address used to access the dashboard?

**Comment by marccampbell** [comment]
@divolgin what do you think is needed here WRT templates?

I imagine that optional buttons would be a nice to have (in scope/out of scope?).

But the current spec refers to a service name and an external and internal port. What are you thinking about?

**Comment by divolgin** [comment]
@marccampbell I thought we template those, but apparently we don't.  So it's not a concern.

**Comment by marccampbell** [comment]
@divolgin is there any additional detail needed here or is this good to go?

**Pull request merged**
