### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by JustinN-Replicated**
#### Which issue(s) this PR fixes:

Fixes #

#### Does this PR introduce a user-facing change?

```release-note

```

### CODE REVIEW

**Comment by JustinN-Replicated** [comment]
@ajp-io I created this with regard to the comments in [sc-35558](https://app.shortcut.com/replicated/story/35558/post-minio-release-supportive-tasks)

**Review by AmberAlston — CHANGES_REQUESTED** [review]
@JustinN-Replicated I couldn't edit directly so I'll drop by suggested edits here. 

1. First line, let's add the words "by default" to be more explicit on default vs opt-out. "...Kubernetes cluster, by default KOTS will leverage...."
2. Let's add the flag info to the line about having the option to use the flag to opt-out. "...case, an optional `--with-minio=false` flag is available....

**Comment by JustinN-Replicated** [comment]
@AmberAlston Sounds good, those are incorporated in the latest

**Review by AmberAlston — APPROVED** [review]
thanks for making those udpates

**Comment by JustinN-Replicated** [comment]
@ajp-io This will need review from someone on @replicatedhq/day1 I believe.  This is part of the details for [sc-37648](https://app.shortcut.com/replicated/story/35558/post-minio-release-supportive-tasks#activity-37648).

**Review by ajp-io — APPROVED** [review]
lgtm

**Comment by ajp-io** [comment]
Who knew we had a day 1 GitHub team. Good to know.

**Comment by ajp-io** [comment]
Are Amber's and my reviews enough, or does someone else need to look at this?

**Review by DanStough — APPROVED** [review]

**Review by DanStough — APPROVED** [review]

**Pull request merged**
