### PR TITLE
Added OKE (Oracle Kubernetes Engine) to distribution support

### LINKED ISSUE #4116: Add support for Oracle Kubernetes Engine (OKE) in the distribution list
We are adding support for Oracle's cloud infrastructure service and need to be able to detect their OKE as an installation target. We would OKE to be detected and present in the distribution enum similar to AKS and EKS.

More specifically:
* The primary goal is that the distribution is available in the templating so we can generate resources customized to Oracle Cloud Infrastructure: `{{- if eq .Values.kubernetes_distribution "oke" }}`
* Secondarily, OKE should be supported on par with other distributions (EKS, AKS, minikube, etc) if possible to avoid introducing developer traps with incomplete support.

### PR DESCRIPTION
**Pull request by jasonmccampbell**
#### What this PR does / why we need it:

Adds support for Oracle Kubernetes Engine to the distribution list. When the kots installer is used with OKE it should correctly identify it as OKE for

#### Which issue(s) this PR fixes:
Fixes #4116 

#### Special notes for your reviewer:
Local testing passes, I'm currently testing it in-cluster. Any feedback on other changes is welcome.

## Steps to reproduce

NA

#### Does this PR introduce a user-facing change?

None

#### Does this PR require documentation?

I don't believe so, but if there is documentation around the distribution enum strings, please let me know.

### CODE REVIEW

**Comment by jasonmccampbell** [comment]
@cbodonnell yes, that's exactly it. We want to be able to tailor some resources, such as storage classes, specifically for OCI. Am I accomplishing that or is more needed to expose the OKE element? Does this put OKE on equal footing w/ EKS, GKE and others?

**Comment by cbodonnell** [comment]
> @cbodonnell yes, that's exactly it. We want to be able to tailor some resources, such as storage classes, specifically for OCI. Am I accomplishing that or is more needed to expose the OKE element? Does this put OKE on equal footing w/ EKS, GKE and others?

Gotcha. This change will make OKE show up in the KOTS instance reporting, but we will need an update to the `github.com/replicatedhq/troubleshoot` go module that's imported to cover the `{{repl Distribution }}` template function.

We'll have to move these commits over to a branch either way to get all of our tests running (having issues with forks at the current moment), so we can use this as a starting point and add the additional pieces once we release `github.com/replicatedhq/troubleshoot` and import the new version. I'll make sure to share any updates with you here.

**Comment by cbodonnell** [comment]
> Do I have rights / should I push to a branch in this repo do you want to create one and I'll move this PR to be against that branch? I'll look at updating troubleshoot this afternoon.

I've gone ahead and created `jasonmccampbell/add-oke-distribution`. You can move this PR against that branch and I'll merge it and open up another against main.

As for troubleshoot, ping here if you open a PR and I'll make sure it gets a review from someone.

**Comment by jasonmccampbell** [comment]
Thank you. I retargetted this PR to the new branch and submitted a PR (1387) to the troubleshoot repo. I can retarget that to a branch as well if you like.

**Comment by cbodonnell** [comment]
> Thank you. I retargetted this PR to the new branch and submitted a PR (1387) to the troubleshoot repo. I can retarget that to a branch as well if you like.

Thanks! Just opened https://github.com/replicatedhq/kots/pull/4119 with this commit and we can get the troubleshoot bump in there too once it's available.

**Pull request merged**
